### ISSUE TITLE
gravity center

### ISSUE THREAD

**Issue by Edwin-Jang** [baivong/watermark#14]
why don't you add "gravity - center" on line number 246 in jquery.watermark.js file with :

case 'c': // Center
gLeft = w / 2 - wmW / 2;
gTop = (h - wmH) / 2;
break;

and thanks for your plugin.
best regards

**Comment by DeepakM02** [comment]
@lelinhtinh  Did you add this functionality ?

**Comment by codeclinic** [comment]
You guys could always do a pull request.

**Comment by lelinhtinh** [comment]
> @lelinhtinh Did you add this functionality ?

3 years for a simple option, what am I doing? 😞

**Comment by codeclinic** [comment]
> > @lelinhtinh Did you add this functionality ?
> 
> 3 years for a simple option, what am I doing?

Did you do a Pull Request?

**Comment by lelinhtinh** [comment]
> 
> 
> > > @lelinhtinh Did you add this functionality ?
> > 
> > 
> > 3 years for a simple option, what am I doing?
> 
> Did you do a Pull Request?

If you can submit a Pull Request, I would be happy to merge it.
