### ISSUE TITLE
how i add multi text

### ISSUE THREAD

**Issue by AhmedHdeawy** [baivong/watermark#17]
hello baivong, thanks for this amazing and easy plugin
can i add multi text ? each text will appear in different position on the same image

**Comment by lelinhtinh** [comment]
Same #3 
https://jsfiddle.net/baivong/4jws7a5d/

**Comment by lelinhtinh** [comment]
Or #11 
https://jsfiddle.net/baivong/0137u9by/

**Comment by AhmedHdeawy** [comment]
thanks, i made simple edit in plugin core file and it works fine
