### ISSUE TITLE
Question: full width/height watermark

### ISSUE THREAD

**Issue by reddo** [baivong/watermark#2]
Hi,

Plugin looks nice, but I have a question: Is there a way to set the watermark to be full width/height of the image? 

I would provide a png larger than the watermarked image and I would like it to be resized to overlay the image completely. Both images would be square. 

Also: does the plugin accept svg as the watermark image?

**Comment by lelinhtinh** [comment]
You mean is this: http://jsfiddle.net/710t9fkp/

**Ps**: If Cross-Origin Resource Sharing policy has allowed, you can use SVG image as the watermark image. 
_Read more_: [CORS enabled image](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)

**Comment by reddo** [comment]
I meant like this: http://jsfiddle.net/710t9fkp/1/

The overlayed image is smaller than the png. 

BTW, I got it to work already, I fiddled with the js file. Let me know if you want to see the changes I made.

**Comment by lelinhtinh** [comment]
Oh, of course.

**Comment by reddo** [comment]
Here's the commit to my fork of the plugin with commented updates: https://github.com/reddo/watermark/commit/363f95d548e960eacf91d40f28958b331725defc#diff-3bf449b4fe7e0a5ff82dd73fb274a1fe

Let me know if you want me to do a pull request.

**Comment by lelinhtinh** [comment]
I found a way to bypass cross-origin, using CORS proxy from http://crossorigin.me/
You can continue to develop this plugin, customize it your way.

Thank you!

**Comment by lelinhtinh** [comment]
I intend to upgrade this plugin, send me, if you were there.

**Comment by reddo** [comment]
I created a pull request. Good luck with the plugin!
