### ISSUE TITLE
Image is saved as ASCII txt format

### ISSUE THREAD

**Issue by kirantpatil** [baivong/watermark#20]
Hi @baivong,

I used your code to send image content via ajax as mentioned in bug https://github.com/amw/jpeg_camera/issues/54.

It is saving content not as jpg but ASCII txt format.

What mistake am I doing here ?

Thanks.

**Comment by lelinhtinh** [comment]
I don't understand Rails, [this link](https://stackoverflow.com/questions/14900038/rails-carrierwave-base64-image-upload) probably helps you.

**Comment by kirantpatil** [comment]
ok. Thanks.
