### ISSUE TITLE
Remove watermark from a particular image

### ISSUE THREAD

**Issue by monukanyal** [baivong/watermark#21]
Hello,

I have multiple images with a watermark but it some condition I want to remove watermark from a particular image, how can I do this? Please help me

**Comment by lelinhtinh** [comment]
Use [`.not( selector )`](http://api.jquery.com/not/). Example:

    $('.img_awesome').not('.img_skip').watermark();

**Comment by monukanyal** [comment]
Thank you, I will check it.
