### ISSUE TITLE
Please add support for External images

### ISSUE THREAD

**Issue by ghost** [baivong/watermark#29]
Getting following error for external images:
"Origin has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by lelinhtinh** [comment]
This cannot be done. It's not my intention, it's a technical problem. JavaScript, or more precisely, the browser doesn't allow this.
See https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy
