### ISSUE TITLE
Can't process same image multiple times

### ISSUE THREAD

**Issue by Diego79** [baivong/watermark#3]
Hello, after a watermark has been applied I can't apply a new one to the same image although path or text were changed.

**Comment by lelinhtinh** [comment]
After a watermark has been applied, this image will have a new URL. You use that URL for the next watermark.

https://jsfiddle.net/baivong/6Lmyanz1/

**Comment by Diego79** [comment]
thank you!

**Comment by Diego79** [comment]
doing some tests it works ok on safari and chrome but firefox only applies the first watermark
