### ISSUE TITLE
.data() issue

### ISSUE THREAD

**Issue by Turtlehead91** [baivong/watermark#5]
Not 100% sure what the issue needs to be resolved.  Might take me a bit to find a solution, as I am still learning the language.  

As a user, I am looking to add watermarks to an image using the URI inline.  The first time I add a watermark, the URI is created and I see an image with a watermark.  The second time I repeat this process, I have the same results.  However, on the third attempt to add a watermark to the image, nothing appears.  No new URI is created.  Any further attempts after this repeat the results of the third attempt. 

Stepping through the process, when an unsuccessful attempt happens, line 280 in jQuery.Watermark.js seems to find existing data.  As such, line 281 is never run. I have attached screenshots of my setup as well.

![image](https://cloud.githubusercontent.com/assets/14916373/13483339/0e0cd124-e0b9-11e5-95d7-917a316fb521.png)

![image](https://cloud.githubusercontent.com/assets/14916373/13483356/2f389356-e0b9-11e5-8aac-899416a74fd4.png)

**Comment by Turtlehead91** [comment]
Not sure of the repercussions, but I simply removed the check for empty data and am letting it over-write any existing data.  Does the trick for me.  I'll keep en eye on this issue if a better solution is found.

**Comment by lelinhtinh** [comment]
Line [280](https://github.com/baivong/watermark/blob/master/dist/jquery.watermark.js#L280) prevents you from using jquery plugin repeated for the same object.

Your issue similar to #3 
See my example for your issue:
https://jsfiddle.net/baivong/5tw6fhdq/

**Comment by Turtlehead91** [comment]
I have a situation in which I would want to use the plugin repeatedly for the same object:
    "As a user I want to add a watermark to an image, and save the image to my webpage.  After seeing the image I decide I no longer wish to show the watermarked image, so I select the original image to show on the page.  Once again I changed my mind and wish to see the image watermarked again."

In this situation I am using the same object multiple times, expecting it to create a new URI for me.

Not trying to sound angry or demanding, just giving you an idea of a simple situation I have run into.  I know I could store the original URI and regurgitate that back to them, but the data starts to add up once I take this use case and multiply it a few times.  I should be fine just leaving the check at line 280 out then.  Thanks for the help!

**Comment by lelinhtinh** [comment]
You can remove lines 280 and 282 without generating any errors. I will find a way to be able to add multi watermark easier in the next version.
