### ISSUE TITLE
The plugin works only once

### ISSUE THREAD

**Issue by jfbvm** [baivong/watermark#6]
First of all, your plugin is incredibly and very very fast!!! Thanks for that!!!

Well, the problem:
I'm using your plugin with a page that capture one or more images from a input tag (the(is) image(s) are loaded on the page on the fly, i'm not using images from server) and apply the watermark to them. The page lets the user the option to edit/rotate the original image loaded, and than apply once more the watermark.
The process starts when a button is clicked and all works fine, the problem is:
If the user click the button more times (when the user change the original image ), the process do not starts again, that is, the water mark is not applied on the same image!

My code is below:

```

$("#makeWaterMarkButton").on("click",function(){
      createWaterMark("","","","img/watermark/logo.png");
});


function createWaterMark(position,opacity,className,path){                    
      if(position == "") position = "se";
      if(opacity == "") opacity = 0.8;
      if(className == "") className = "watermark";
      if(path == "") path = "img/watermark/logo_ananeriday.png";

      $("."+className).watermark({
            path: path,
            opacity: opacity,
            gravity: position,
            margin: 0
      });
}
```

**Comment by lelinhtinh** [comment]
This plugin is designed to not run again on the same object, in order to avoid reduced performance.
In your case, you need to create a virtual DOM image object, add watermark on it, then replace the image link (with watermark) to the original image.

``` js
function createWaterMark(position, opacity, className, path) {
    if (position == "") position = "se";
    if (opacity == "") opacity = 0.8;
    if (className == "") className = "watermark";
    if (path == "") path = "https://i.imgur.com/LcpZHu5.png";

    var $image = $("." + className);

    $('<img>', {
        src: $image.attr('src')
    }).watermark({
        path: path,
        opacity: opacity,
        gravity: position,
        margin: 0,
        done: function(imgURL) {
            $image.attr('src', imgURL);
        }
    });
}

$("#makeWaterMarkButton").on("click", function() {
    createWaterMark("", "", "", "https://i.imgur.com/LcpZHu5.png");
});
```

Try it https://jsfiddle.net/baivong/Ld4yzz38/
