### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by ozbilgic** [baivong/watermark#7]
I did everything but does not work. I see your demo, it does not work.

**Comment by lelinhtinh** [comment]
[What Browser do you use? Is Javascript enabled?](http://www.whatsmybrowser.org/)

**Comment by ozbilgic** [comment]
http://imageshack.com/a/img924/140/fn6seW.png

**Comment by lelinhtinh** [comment]
![demo](https://cloud.githubusercontent.com/assets/5460915/15626688/917e859a-24f5-11e6-9b72-9fb9f5c50202.jpg)

On the demo page, do you look like this?

**Comment by ozbilgic** [comment]
Working demo on your page. [This demo does not work.](https://github.com/baivong/watermark/tree/master/demo)
Can you show a working example? I would be most grateful.
http://jsfiddle.net/

**Comment by lelinhtinh** [comment]
Demo here: https://rawgit.com/baivong/watermark/master/demo/index.html

**Comment by ozbilgic** [comment]
Thank you so much for your help. It is working.
