### ISSUE TITLE
Gif is not animating now

### ISSUE THREAD

**Issue by azzzey5** [baivong/watermark#9]
I am not sure if this is an issue, consider it as a doubt. I tried it with an animated gif, the anime lost it's animated behaviour after watermark. 

Any solution for this ?

**Comment by lelinhtinh** [comment]
This plugin is based on html5 canvas, so it just can output images to jpeg, png and webp.

> JavaScript has no way of controlling the current frame of an Animated GIF
> http://stackoverflow.com/a/4648281
